INSERT INTO tblRoutes (
        routeName,
        routeComponentName,
        routeComponentLocation,
        routeUrl,
        routeIsPrivate
    )
VALUES ('Dashboard', 'Analytics', 'Analytics', '/', '1'),
    (
        'Dashboard Index',
        'Analytics',
        'Analytics',
        '/index',
        '1'
    ),
    (
        'Analytics',
        'Analytics',
        'Analytics',
        '/analytics',
        '1'
    ),
    ('Finance', 'Finance', 'Finance', '/finance', '1'),
    ('Crypto', 'Crypto', 'Crypto', '/crypto', '1'),
    (
        'Todo List',
        'Todolist',
        'Apps/Todolist',
        '/apps/todolist',
        '1'
    ),
    (
        'Notes',
        'Notes',
        'Apps/Notes',
        '/apps/notes',
        '1'
    ),
    (
        'Contacts',
        'Contacts',
        'Apps/Contacts',
        '/apps/contacts',
        '1'
    ),
    (
        'Mailbox',
        'Mailbox',
        'Apps/Mailbox',
        '/apps/mailbox',
        '1'
    ),
    (
        'Invoice List',
        'List',
        'Apps/Invoice/List',
        '/apps/invoice/list',
        '1'
    ),
    ('Chat', 'Chat', 'Apps/Chat', '/apps/chat', '1'),
    (
        'Scrumboard',
        'Scrumboard',
        'Apps/Scrumboard',
        '/apps/scrumboard',
        '1'
    ),
    (
        'Calendar',
        'Calendar',
        'Apps/Calendar',
        '/apps/calendar',
        '1'
    ),
    (
        'Invoice Preview',
        'Preview',
        'Apps/Invoice/Preview',
        '/apps/invoice/preview',
        '1'
    ),
    (
        'Invoice Add',
        'Add',
        'Apps/Invoice/Add',
        '/apps/invoice/add',
        '1'
    ),
    (
        'Invoice Edit',
        'Edit',
        'Apps/Invoice/Edit',
        '/apps/invoice/edit',
        '1'
    ),
    (
        'Tabs',
        'Tabs',
        'Components/Tabs',
        '/components/tabs',
        '1'
    ),
    (
        'Accordions',
        'Accordians',
        'Components/Accordians',
        '/components/accordions',
        '1'
    ),
    (
        'Modals',
        'Modals',
        'Components/Modals',
        '/components/modals',
        '1'
    ),
    (
        'Cards',
        'Cards',
        'Components/Cards',
        '/components/cards',
        '1'
    ),
    (
        'Carousel',
        'Carousel',
        'Components/Carousel',
        '/components/carousel',
        '1'
    ),
    (
        'Countdown',
        'Countdown',
        'Components/Countdown',
        '/components/countdown',
        '1'
    ),
    (
        'Counter',
        'Counter',
        'Components/Counter',
        '/components/counter',
        '1'
    ),
    (
        'Sweet Alert',
        'SweetAlert',
        'Components/SweetAlert',
        '/components/sweetalert',
        '1'
    ),
    (
        'Timeline',
        'Timeline',
        'Components/Timeline',
        '/components/timeline',
        '1'
    ),
    (
        'Notifications',
        'Notification',
        'Components/Notification',
        '/components/notifications',
        '1'
    ),
    (
        'Media Object',
        'MediaObject',
        'Components/MediaObject',
        '/components/media-object',
        '1'
    ),
    (
        'List Group',
        'ListGroup',
        'Components/ListGroup',
        '/components/list-group',
        '1'
    ),
    (
        'Pricing Table',
        'PricingTable',
        'Components/PricingTable',
        '/components/pricing-table',
        '1'
    ),
    (
        'LightBox',
        'LightBox',
        'Components/LightBox',
        '/components/lightbox',
        '1'
    ),
    (
        'Alerts',
        'Alerts',
        'Elements/Alerts',
        '/elements/alerts',
        '1'
    ),
    (
        'Avatar',
        'Avatar',
        'Elements/Avatar',
        '/elements/avatar',
        '1'
    ),
    (
        'Badges',
        'Badges',
        'Elements/Badges',
        '/elements/badges',
        '1'
    ),
    (
        'Breadcrumbs',
        'Breadcrumbs',
        'Elements/Breadcrumbs',
        '/elements/breadcrumbs',
        '1'
    ),
    (
        'Buttons',
        'Buttons',
        'Elements/Buttons',
        '/elements/buttons',
        '1'
    ),
    (
        'Button Groups',
        'Buttongroups',
        'Elements/Buttongroups',
        '/elements/buttons-group',
        '1'
    ),
    (
        'Color Library',
        'Colorlibrary',
        'Elements/Colorlibrary',
        '/elements/color-library',
        '1'
    ),
    (
        'Dropdown',
        'DropdownPage',
        'Elements/DropdownPage',
        '/elements/dropdown',
        '1'
    ),
    (
        'Infobox',
        'Infobox',
        'Elements/Infobox',
        '/elements/infobox',
        '1'
    ),
    (
        'Jumbotron',
        'Jumbotron',
        'Elements/Jumbotron',
        '/elements/jumbotron',
        '1'
    ),
    (
        'Loader',
        'Loader',
        'Elements/Loader',
        '/elements/loader',
        '1'
    ),
    (
        'Pagination',
        'Pagination',
        'Elements/Pagination',
        '/elements/pagination',
        '1'
    ),
    (
        'Popovers',
        'Popovers',
        'Elements/Popovers',
        '/elements/popovers',
        '1'
    ),
    (
        'Progress Bar',
        'Progressbar',
        'Elements/Progressbar',
        '/elements/progress-bar',
        '1'
    ),
    (
        'Search',
        'Search',
        'Elements/Search',
        '/elements/search',
        '1'
    ),
    (
        'Tooltips',
        'Tooltip',
        'Elements/Tooltip',
        '/elements/tooltips',
        '1'
    ),
    (
        'Treeview',
        'Treeview',
        'Elements/Treeview',
        '/elements/treeview',
        '1'
    ),
    (
        'Typography',
        'Typography',
        'Elements/Typography',
        '/elements/typography',
        '1'
    ),
    ('Charts', 'Charts', 'Charts', '/charts', '1'),
    ('Widgets', 'Widgets', 'Widgets', '/widgets', '1'),
    (
        'Font Icons',
        'FontIcons',
        'FontIcons',
        '/font-icons',
        '1'
    ),
    (
        'Drag And Drop',
        'DragAndDrop',
        'DragAndDrop',
        '/dragndrop',
        '1'
    ),
    ('Tables', 'Tables', 'Tables', '/tables', '1'),
    (
        'Data Tables Basic',
        'Basic',
        'DataTables/Basic',
        '/datatables/basic',
        '1'
    ),
    (
        'Data Tables Advanced',
        'Advanced',
        'DataTables/Advanced',
        '/datatables/advanced',
        '1'
    ),
    (
        'Data Tables Skin',
        'Skin',
        'DataTables/Skin',
        '/datatables/skin',
        '1'
    ),
    (
        'Data Tables Order Sorting',
        'OrderSorting',
        'DataTables/OrderSorting',
        '/datatables/order-sorting',
        '1'
    ),
    (
        'Data Tables Multi Column',
        'MultiColumn',
        'DataTables/MultiColumn',
        '/datatables/multi-column',
        '1'
    ),
    (
        'Data Tables Multiple Tables',
        'MultipleTables',
        'DataTables/MultipleTables',
        '/datatables/multiple-tables',
        '1'
    ),
    (
        'Data Tables Alt Pagination',
        'AltPagination',
        'DataTables/AltPagination',
        '/datatables/alt-pagination',
        '1'
    ),
    (
        'Data Tables Checkbox',
        'Checkbox',
        'DataTables/Checkbox',
        '/datatables/checkbox',
        '1'
    ),
    (
        'Data Tables Range Search',
        'RangeSearch',
        'DataTables/RangeSearch',
        '/datatables/range-search',
        '1'
    ),
    (
        'Data Tables Export',
        'Export',
        'DataTables/Export',
        '/datatables/export',
        '1'
    ),
    (
        'Data Tables Column Chooser',
        'ColumnChooser',
        'DataTables/ColumnChooser',
        '/datatables/column-chooser',
        '1'
    ),
    (
        'Profile',
        'Profile',
        'Users/Profile',
        '/users/profile',
        '1'
    ),
    (
        'User Account Settings',
        'AccountSetting',
        'Users/AccountSetting',
        '/users/user-account-settings',
        '1'
    ),
    (
        'Knowledge Base',
        'KnowledgeBase',
        'Pages/KnowledgeBase',
        '/pages/knowledge-base',
        '1'
    ),
    (
        'Contact Us Boxed',
        'ContactUsBoxed',
        'Pages/ContactUsBoxed',
        '/pages/contact-us-boxed',
        '0'
    ),
    (
        'Contact Us Cover',
        'ContactUsCover',
        'Pages/ContactUsCover',
        '/pages/contact-us-cover',
        '0'
    ),
    ('FAQ', 'Faq', 'Pages/Faq', '/pages/faq', '1'),
    (
        'Coming Soon Boxed',
        'ComingSoonBoxed',
        'Pages/ComingSoonBoxed',
        '/pages/coming-soon-boxed',
        '0'
    ),
    (
        'Coming Soon Cover',
        'ComingSoonCover',
        'Pages/ComingSoonCover',
        '/pages/coming-soon-cover',
        '0'
    ),
    (
        'Error 404',
        'ERROR404',
        'Pages/Error404',
        '/pages/error404',
        '0'
    ),
    (
        'Error 500',
        'ERROR500',
        'Pages/Error500',
        '/pages/error500',
        '0'
    ),
    (
        'Error 503',
        'ERROR503',
        'Pages/Error503',
        '/pages/error503',
        '0'
    ),
    (
        'Maintenence',
        'Maintenence',
        'Pages/Maintenence',
        '/pages/maintenence',
        '0'
    ),
    (
        'Boxed Sign In',
        'LoginBoxed',
        'Authentication/LoginBoxed',
        '/auth/boxed-signin',
        '0'
    ),
    (
        'Boxed Sign Up',
        'RegisterBoxed',
        'Authentication/RegisterBoxed',
        '/auth/boxed-signup',
        '0'
    ),
    (
        'Boxed Lockscreen',
        'UnlockBoxed',
        'Authentication/UnlockBox',
        '/auth/boxed-lockscreen',
        '0'
    ),
    (
        'Boxed Password Reset',
        'RecoverIdBoxed',
        'Authentication/RecoverIdBox',
        '/auth/boxed-password-reset',
        '0'
    ),
    (
        'Cover Login',
        'LoginCover',
        'Authentication/LoginCover',
        '/auth/cover-login',
        '0'
    ),
    (
        'Cover Register',
        'RegisterCover',
        'Authentication/RegisterCover',
        '/auth/cover-register',
        '0'
    ),
    (
        'Cover Lockscreen',
        'UnlockCover',
        'Authentication/UnlockCover',
        '/auth/cover-lockscreen',
        '0'
    ),
    (
        'Cover Password Reset',
        'RecoverIdCover',
        'Authentication/RecoverIdCover',
        '/auth/cover-password-reset',
        '0'
    ),
    (
        'Form Basic',
        'FormBasic',
        'Forms/Basic',
        '/forms/basic',
        '1'
    ),
    (
        'Form Input Group',
        'FormInputGroup',
        'Forms/InputGroup',
        '/forms/input-group',
        '1'
    ),
    (
        'Form Layouts',
        'FormLayouts',
        'Forms/Layouts',
        '/forms/layouts',
        '1'
    ),
    (
        'Validation',
        'Validation',
        'Forms/Validation',
        '/forms/validation',
        '1'
    ),
    (
        'Input Mask',
        'InputMask',
        'Forms/InputMask',
        '/forms/input-mask',
        '1'
    ),
    (
        'Select2',
        'Select2',
        'Forms/Select2',
        '/forms/select2',
        '1'
    ),
    (
        'Touchspin',
        'Touchspin',
        'Forms/TouchSpin',
        '/forms/touchspin',
        '1'
    ),
    (
        'Checkbox Radio',
        'CheckBoxRadio',
        'Forms/CheckboxRadio',
        '/forms/checkbox-radio',
        '1'
    ),
    (
        'Switches',
        'Switches',
        'Forms/Switches',
        '/forms/switches',
        '1'
    ),
    (
        'Wizards',
        'Wizards',
        'Forms/Wizards',
        '/forms/wizards',
        '1'
    ),
    (
        'File Upload Preview',
        'FileUploadPreview',
        'Forms/FileUploadPreview',
        '/forms/file-upload',
        '1'
    ),
    (
        'Quill Editor',
        'QuillEditor',
        'Forms/QuillEditor',
        '/forms/quill-editor',
        '1'
    ),
    (
        'Markdown Editor',
        'MarkDownEditor',
        'Forms/MarkDownEditor',
        '/forms/markdown-editor',
        '1'
    ),
    (
        'Date Picker',
        'DateRangePicker',
        'Forms/DateRangePicker',
        '/forms/date-picker',
        '1'
    ),
    (
        'Clipboard',
        'Clipboard',
        'Forms/Clipboard',
        '/forms/clipboard',
        '1'
    ),
    ('About', 'About', 'About', '/about', '1'),
    (
        'Error',
        'Error',
        'components/Error',
        '/error',
        '1'
    );